name: Publish

on:
  push:
    branches: [source]
  workflow_run:
    workflows: [Webmentions]
    branches: [source]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('composer.lock') }}

    - name: Install Composer Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Install NPM Dependencies
      run: npm install

    - name: Build Site
      run: npm run production

    - name: Create CNAME File
      run: echo "moonbaselabs.com" >> build_production/CNAME

    - name: Stage Files
      run: git add -f build_production

    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git commit -m "Build for deploy"

    - name: Publish
      run: |
        git subtree split --prefix build_production -b production
        git push -f origin production:production
        git branch -D production
